# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160713_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=120),
        ),
    ]
